image: Visual Studio 2017
build_script:
- ps: >-
    [xml]$doc = (Get-Content .\MBW.Libraries.DeviceObjectLib\MBW.Libraries.DeviceObjectLib.csproj)

    [string]$version = $doc.Project.PropertyGroup.VersionPrefix
    
    Update-AppveyorBuild -Version "$($version.Trim()).$env:APPVEYOR_BUILD_NUMBER"
- ps: dotnet build --no-restore -c Release
- ps: dotnet pack --no-build -c Release --include-symbols
install:
- dotnet restore
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: dVL99Rr5F6Z2L2ToaN/B38cKyDE3I+jzYPeieKPTMNjTRzf6D+stLOZB7t+p4OuW
  on:
    branch: nuget