image: Visual Studio 2017
build_script:
- ps: >-
    [xml]$doc = (Get-Content .\DeviceObjectLib\DeviceObjectLib.csproj)

    [string]$version = $doc.Project.PropertyGroup.VersionPrefix
    
    Update-AppveyorBuild -Version "$($version.Trim()).$env:APPVEYOR_BUILD_NUMBER"
- ps: # Library
- ps: msbuild /t:Build /p:Configuration=Release DeviceObjectLib
- ps: # Pack Library
- ps: msbuild /t:Pack /p:Configuration=Release /p:OutputPath=..\Nuget\ DeviceObjectLib
- ps: # Utilities
- ps: msbuild /t:Build /p:Configuration=Release Examples\ListAllObjects
- ps: msbuild /t:Build /p:Configuration=Release Examples\ListAllObjectsAndLinks
- ps: msbuild /t:Build /p:Configuration=Release Examples\ShowObjectTypes
install:
- msbuild /t:Restore
artifacts:
- path: Nuget\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: dgfUEGXULcqCTyNcS6UEDK8BCBi8y+M2+d4IFjnb3Gf9DqV34fMSp1XjxJg2AVRC
  on:
    branch: nuget