version: 0.1.0.{build}-alpha
build_script:
- cmd: >-
    REM Core

    dotnet restore

    dotnet pack -c Release -o Nuget\ DeviceObjectLib



    REM Utilities

    dotnet build -c Release DemoApp
artifacts:
- path: Nuget\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: dgfUEGXULcqCTyNcS6UEDK8BCBi8y+M2+d4IFjnb3Gf9DqV34fMSp1XjxJg2AVRC
  on:
    branch: nuget